# Copyright (C) 2018 DingYi <dingyi139@gmail.com>
#
# This is free software, licensed under the GNU General Public License v3.
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI support for V2ray Server
LUCI_DEPENDS:=+unzip
LUCI_PKGARCH:=all

PKG_NAME:=luci-app-xray-server
PKG_VERSION:=1.0
PKG_RELEASE:=68

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
